### ISSUE TITLE
Print the Outputs

### ISSUE THREAD

**Issue by Nagarjunadik7** [nimeshkverma/mongo_joins#9]
How to print the results of join ??

**Comment by nimeshkverma** [comment]
>>> from mongojoin.mongojoin import MongoJoin
	>>> from mongojoin.mongojoin import MongoCollection
	>>> collection_1 = MongoCollection("test", "supplier", ["supplier_id", "name"], {"supplier_id": 1001})
	>>> collection_2 = MongoCollection("test", "order", ["supplier_id", "qty"], {"supplier_id": 1001}, host='localhost')
	>>> aggregator = MongoJoin(collection_1, collection_2, ["supplier_id"])


The join commands return a `DefaultDict` object which can be used accordingly.
To perform inner join, 
	
	>>> join_output_dict = aggregator.inner()

To perform left-outer join,
	
	>>> join_output_dict =  aggregator.left_outer()

To perform right-outer join,
	
	>>> join_output_dict =  aggregator.right_outer()

To perform full-outer join,
	
	>>> join_output_dict =  aggregator.full_outer()

use `join_output_dict` to print the join
